---
title: "Felkészítő\n\nAlelnök részére"
output-file: "alelnok_felkeszito_esemeny.docx"
subtitle: "Tárgy: Adott eseményről egy rövid beszélő cím"
format:
  docx:
    reference-doc: _extensions/memo.docx
knitr:
    opts_chunk: 
        echo: false
        message: false
        eval: true
        collapse: true
        dev: "svg"
        dev.args:
            bg: "transparent"
        comment: "#>"
        fig.height: 6
        fig.width: 8
        fig.align: "center"
language:
    crossref-fig-title: "Ábra"
    crossref-tbl-title: "Táblázat"
---

# I. fejezet

- **következtetések:** minden oké!

```{r}
#| include: false
library(tidyverse)
library(mnbplots)
options(lang = "hu")

theme_set(theme_mnb_ts(base_size = 16))
update_geom_defaults("line", list(linewidth = 1.2, color = mnb_colors(1)))
update_geom_defaults("rect", list(fill = "lightblue", color = "black"))
update_geom_defaults("point", list(size = 2, color = mnb_colors(1)))
```

```{r}
#| label: fig-minta
#| fig-cap: Beszélő cím
plot(cars)
```

